fix(trans): add missing domain in translations
PrestaShop/ps_themecusto pull request #59
Opened 2023-05-11 15:59 UTC by tleon

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | The new $this->trans() introduced in #56 method were missing the domain parameter. This fixes it.
| Type?         | bug fix
| BC breaks?    |  no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#32266.
| How to test?  | Go to BO > Design > Theme & Logo > Click on Pages Configuration > No more exception

2023-05-11 16:25 UTC, matks reviewed
CI is failing 😄

2023-05-12 08:42 UTC, nicosomb requested changes

2023-05-12 08:42 UTC, nicosomb commented on controllers/admin/AdminPsThemeCustoConfiguration.php
> +            exit($this->trans('You do not have permission to edit this.'), [], 'Modules.PsThemeCusto.Admin');
```suggestion
            exit($this->trans('You do not have permission to edit this.', [], 'Modules.PsThemeCusto.Admin'));
```

2023-05-15 10:35 UTC, lartist approved these changes

2023-05-15 14:01 UTC, boherm approved these changes
LGTM, thanks @tleon!

2023-05-15 14:12 UTC, merged